# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'CentOS-6.4-x86_64'
  config.vm.box_url = 'https://github.com/2creatives/vagrant-centos/releases/download/v6.4.2/centos64-x86_64-20140116.box'
  config.vm.network 'private_network', ip: '10.100.100.106'
  config.vm.synced_folder '../', '/vagrant_data', :mount_options => %w(dmode=777 fmode=777)
  config.vm.hostname = 'redmine'
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
    vb.customize ['modifyvm', :id, '--memory', '2048']
    vb.name = 'redmine'
  end
  config.vm.provision 'chef_solo' do |chef|
    chef.cookbooks_path = %w(cookbooks site-cookbooks)
    chef.roles_path = 'roles'
    chef.add_role 'redmine-alminium'
  end
end
